/**Copyright GET / ENST / Ludovic Apvrille

ludovic.apvrille at enst.fr

This software is a computer program whose purpose is to edit TURTLE
diagrams, generate RT-LOTOS code from these TURTLE diagrams, and at
last to analyse results provided from externalm formal validation tools.

This software is governed by the CeCILL  license under French law and
abiding by the rules of distribution of free software.  You can  use, 
modify and/ or redistribute the software under the terms of the CeCILL
license as circulated by CEA, CNRS and INRIA at the following URL
"http://www.cecill.info". 

As a counterpart to the access to the source code and rights to copy,
modify and redistribute granted by the license, users are provided only
with a limited warranty  and the software's author,  the holder of the
economic rights,  and the successive licensors  have only  limited
liability. 

In this respect, the user's attention is drawn to the risks associated
with loading,  using,  modifying and/or developing or reproducing the
software by the user in light of its specific status of free software,
that may mean  that it is complicated to manipulate,  and  that  also
therefore means  that it is reserved for developers  and  experienced
professionals having in-depth computer knowledge. Users are therefore
encouraged to load and test the software's suitability as regards their
requirements in conditions enabling the security of their systems and/or 
data to be ensured and,  more generally, to use and operate it in the 
same conditions as regards security. 

The fact that you are presently reading this means that you have had
knowledge of the CeCILL license and that you accept its terms.*/

package compiler.tmlparser;

/* Generated By:JJTree: Do not edit this line. ./TMLExprParserTreeConstants.java */

package compiler.tmlgrammar;

public interface TMLExprParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTEXPRESSION = 1;
  public int JJTNAT_ASSIGN = 2;
  public int JJTNATEXTENDEDEXPRESSION = 3;
  public int JJTNAT_ID = 4;
  public int JJTQUEUE_NAT_ID = 5;
  public int JJTBOOL_ID = 6;
  public int JJTNAT_QUEUE_NAT_FUNC = 7;
  public int JJTNATOPERATOREXTENDEDEXPRESSION = 8;
  public int JJTNAT_OP = 9;
  public int JJTQUEUENATEXTENDEDEXPRESSION = 10;
  public int JJTQUEUE_NAT_FUNC = 11;
  public int JJTBOOLEXTENDEDEXPRESSION = 12;
  public int JJTBOOLOPERATOREXTENDEDEXPRESSION = 13;
  public int JJTBOOLFUNCTION1 = 14;
  public int JJTBOOL_FUNC = 15;
  public int JJTBOOL_QUEUE_NAT_FUNC = 16;
  public int JJTID = 17;
  public int JJTLPAREN = 18;
  public int JJTRPAREN = 19;
  public int JJTBOOL_OP = 20;
  public int JJTNAT_COMP = 21;
  public int JJTBOOLNAT_COMP = 22;
  public int JJTACTIONGATE = 23;
  public int JJTACTIONGATE2 = 24;
  public int JJTACTIONGATEVALUE = 25;
  public int JJTACTIONGATEVALUE2 = 26;
  public int JJTACTIONGATEVALUE3 = 27;
  public int JJTTYPE = 28;
  public int JJTNAT_VALUE = 29;
  public int JJTLITERAL = 30;
  public int JJTQUEUENATLITERAL = 31;
  public int JJTBOOLEANLITERAL = 32;


  public String[] jjtNodeName = {
    "Root",
    "Expression",
    "NAT_ASSIGN",
    "NatExtendedExpression",
    "NAT_ID",
    "QUEUE_NAT_ID",
    "BOOL_ID",
    "NAT_QUEUE_NAT_FUNC",
    "NatOperatorExtendedExpression",
    "NAT_OP",
    "QueueNatExtendedExpression",
    "QUEUE_NAT_FUNC",
    "BoolExtendedExpression",
    "BoolOperatorExtendedExpression",
    "BoolFunction1",
    "BOOL_FUNC",
    "BOOL_QUEUE_NAT_FUNC",
    "ID",
    "LPAREN",
    "RPAREN",
    "BOOL_OP",
    "NAT_COMP",
    "BOOLNAT_COMP",
    "ActionGate",
    "ActionGate2",
    "ActionGateValue",
    "ActionGateValue2",
    "ActionGateValue3",
    "TYPE",
    "NAT_VALUE",
    "Literal",
    "QueueNatLiteral",
    "BooleanLiteral",
  };
}
