
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20210814 (GIT d69c832)
//----------------------------------------------------

package myutil.intboolsolver;

/** CUP generated class containing symbol constants. */
public class IBSStdParserSym {
  /* terminals */
  public static final int GEQ = 14;
  public static final int MOD = 6;
  public static final int AND = 7;
  public static final int LT = 11;
  public static final int PLUS = 2;
  public static final int INT = 20;
  public static final int OR = 8;
  public static final int NOT = 15;
  public static final int GT = 12;
  public static final int PARSE_INT = 18;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int DIV = 5;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int BOOL = 21;
  public static final int PARSE_BOOL = 19;
  public static final int LEQ = 13;
  public static final int RPAR = 17;
  public static final int LPAR = 16;
  public static final int DIF = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "EQ",
  "DIF",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "NOT",
  "LPAR",
  "RPAR",
  "PARSE_INT",
  "PARSE_BOOL",
  "INT",
  "BOOL"
  };
}

